# Generated by Django 3.2.7 on 2021-09-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rent_type',
            field=models.CharField(blank=True, choices=[('not_applicable', 'not_applicable'), ('hourly', 'hourly'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_rented',
            field=models.BooleanField(default=False, editable=False, verbose_name='Is the product on rent?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_sold',
            field=models.BooleanField(default=False, editable=False, verbose_name='Is the product sold?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rent'),
        ),
    ]
