# Generated by Django 3.2.7 on 2021-09-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210907_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='sold_at',
            field=models.DateTimeField(null=True, verbose_name='Selling Time'),
        ),
    ]
