# Generated by Django 3.2.7 on 2021-09-07 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_alter_sellproduct_sold_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='is_rented',
            field=models.BooleanField(default=False, verbose_name='Is the product on rent?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='Is the product sold?'),
        ),
        migrations.AlterField(
            model_name='rentproduct',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed', to=settings.AUTH_USER_MODEL, verbose_name='Product Borrower'),
        ),
        migrations.AlterField(
            model_name='rentproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lent', to='product.product', verbose_name='Product to Rent'),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought', to=settings.AUTH_USER_MODEL, verbose_name='Product Buyer'),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold', to='product.product', verbose_name='Product Sold'),
        ),
    ]
